name: 🚧 Feature
description: Create a new feature request
title: 🚧 <title>
labels: ["feature"]
body:
  - type: input
    id: due-date
    attributes:
      label: "Due Date"
      description: Enter a completion date
  - type: input
    id: request
    attributes:
      label: "Requested By"
      description: Who requested this feature?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Overview"
      description: Please enter an overview of the feature
      placeholder: Details of the proposed feature
    validations:
      required: true
  - type: textarea
    id: endpoint
    attributes:
      label: "Endpoint"
      description: State the endpoint, request and response
      value: |
        GET /
      
        #### Request
        
        ````json
        {}
        ````
        
        #### Response
        200
        ```json
        {}
        ```
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Steps"
      description: Add steps required to complete the feature
    validations:
      required: false
